const fs = require('fs');
const assert = require('node:assert/strict');
const vm = require('vm');
const {JSDOM} = require('jsdom');
const {PGlite} = require('@electric-sql/pglite');
const root = __dirname + '/../';
const teacher1 = '11111111-1111-4111-8111-111111111111';
const teacher2 = '22222222-2222-4222-8222-222222222222';
async function main() {
  const db = new PGlite();
  await db.exec(`create schema auth; create role anon; create role authenticated;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth, public to anon, authenticated;
    create table public.submissions(id uuid); create table public.class_gates(id uuid);
    grant all on public.submissions, public.class_gates to anon,authenticated;`);
  const sql = fs.readFileSync(root+'supabase_v3.sql','utf8');
  await db.exec(sql); await db.exec(sql); // Migration must be repeatable.
  await db.exec(`insert into auth.users values ('${teacher1}'),('${teacher2}'); insert into public.teacher_profiles(user_id) select id from auth.users;`);
  const as = async (role,id='') => db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role ${role};`);
  const query = async (sql,args) => (await db.query(sql,args)).rows;
  await as('authenticated',teacher1);
  const c1 = (await query("select public.create_course('9a Geschichte',2) id"))[0].id;
  const s1 = await query('select * from public.course_students order by seat');
  assert.equal(s1.length,2); assert.match(s1[0].access_code,/^[0123456789abcdefghjkmnpqrstvwxyz]{8}$/); assert.notEqual(s1[0].access_code,s1[1].access_code);
  await db.exec('reset role');
  const legacyCode = 'abcdef0123456789abcdef01';
  await query('update public.course_students set access_code=$1 where id=$2',[legacyCode,s1[1].id]);
  await db.exec(sql); // Existing long codes survive the upgrade.
  await as('anon');
  assert.equal((await query('select public.student_context($1) data',[legacyCode]))[0].data.student_id,s1[1].id);
  await as('authenticated',teacher1);
  assert.match((await query('select public.replace_student_code($1) code',[s1[1].id]))[0].code,/^[0123456789abcdefghjkmnpqrstvwxyz]{8}$/);
  await as('anon');
  await assert.rejects(query('select public.student_context($1)',[legacyCode]));
  await as('authenticated',teacher2);
  assert.equal((await query('select * from public.courses')).length,0);
  const c2 = (await query("select public.create_course('9a Geschichte',1) id"))[0].id;
  assert.notEqual(c1,c2);
  assert.equal((await query('select * from public.course_students')).length,1);
  assert.equal((await query('update public.courses set exchange_open=true where id=$1 returning id',[c1])).length,0);
  await assert.rejects(query('select public.replace_student_code($1)',[s1[0].id]));
  await as('anon');
  await assert.rejects(query('select * from public.course_students'));
  await assert.rejects(query('select * from public.course_submissions'));
  await assert.rejects(query('select * from public.submissions'));
  await assert.rejects(query("select public.create_course('bad',2)"));
  await assert.rejects(query("select public.student_context('wrong')"));
  let context = (await query('select public.student_context($1) data',[s1[0].access_code]))[0].data;
  assert.equal(context.course_id,c1); assert.equal(context.exchange_open,false);
  await query("select public.submit_course_work($1,'A',$2::jsonb)",[s1[0].access_code,JSON.stringify({museum_vorgehen:'Test',student_name:'NEVER STORE',course_id:c2})]);
  await query("select public.submit_course_work($1,'B',$2::jsonb)",[s1[0].access_code,JSON.stringify({museum_vorgehen:'Updated',student_name:'NEVER STORE',course_id:c2})]);
  await assert.rejects(query("select public.submit_course_work($1,'X','{}')",[s1[0].access_code]));
  await assert.rejects(query("select public.submit_course_work($1,'A','[]')",[s1[0].access_code]));
  await as('authenticated',teacher2);
  assert.equal((await query('select * from public.course_submissions')).length,0);
  await as('authenticated',teacher1);
  let subs=await query('select * from public.course_submissions');
  assert.equal(subs.length,1); assert.equal(subs[0].group_code,'B'); assert.equal(subs[0].answers.student_name,undefined); assert.equal(subs[0].answers.course_id,undefined);
  await query('update public.course_submissions set reviewed=true');
  await assert.rejects(query("update public.course_submissions set answers='{}'"));
  await query('update public.courses set exchange_open=true where id=$1',[c1]);
  const newCode = (await query('select public.replace_student_code($1) code',[s1[0].id]))[0].code;
  assert.notEqual(newCode,s1[0].access_code);
  await as('anon');
  await assert.rejects(query('select public.student_context($1)',[s1[0].access_code]));
  await assert.rejects(query("select public.submit_course_work($1,'A','{}')",[s1[0].access_code]));
  assert.equal((await query('select public.student_context($1) data',[newCode]))[0].data.exchange_open,true);
  await query("select public.submit_course_work($1,'A','{}')",[newCode]);
  await as('authenticated',teacher1);
  subs=await query('select * from public.course_submissions'); assert.equal(subs.length,1); assert.equal(subs[0].reviewed,false);
  await query('update public.courses set exchange_open=false');
  await as('anon');
  assert.equal((await query('select public.student_context($1) data',[newCode]))[0].data.exchange_open,false);
  await db.close();
  console.log('PASS: migration rerun, teacher isolation, anonymous denial, validation, code rotation, upsert, metadata stripping and course gates');

  for (const file of ['teacher.js','api.js','sw.js']) new vm.Script(fs.readFileSync(root+file,'utf8'));
  const page=fs.readFileSync(root+'index.html','utf8');
  const code=page.match(/<script>([\s\S]*?)<\/script>/)[1]; new vm.Script(code);
  const dom = new JSDOM(page,{url:'https://school.test/',runScripts:'outside-only',pretendToBeVisual:true});
  const w=dom.window; w.scrollTo=()=>{}; w.HTMLElement.prototype.scrollIntoView=()=>{};
  let gate=false, sent;
  w.SchoolAPI={formatCode:v=>v,normalizeCode:v=>v,rpc:async(name,data)=>{if(name==='submit_course_work'){sent=data;return 'ok'}return {course_id:c1,exchange_open:gate}}};
  w.sessionStorage.setItem('clara-student-v3',JSON.stringify({student_id:s1[0].id,course_id:c1,course_name:'9a',seat:1,code:newCode}));
  w.eval(code+'\nwindow.testState = state;');
  await w.eval('checkGate()');
  assert.equal(w.eval('gateUnlocked()'),false);
  gate=true; await w.eval('checkGate()'); assert.equal(w.eval('gateUnlocked()'),true);
  w.setGroup('A'); w.testState.answers.student_name='Old name'; w.testState.answers.museum_vorgehen='Test';
  await w.eval('submitResults()'); assert.equal(sent.p_code,newCode); assert.equal(sent.p_answers.student_name,undefined);
  gate=false; await w.eval('checkGate()'); assert.equal(w.eval('gateUnlocked()'),false);
  assert.equal(w.document.querySelectorAll('[data-save="student_name"],[data-save="class_code"]').length,0);
  dom.window.close();
  const guest=new JSDOM(page,{url:'https://school.test/',runScripts:'outside-only',pretendToBeVisual:true});
  guest.window.scrollTo=()=>{};guest.window.HTMLElement.prototype.scrollIntoView=()=>{};guest.window.SchoolAPI=w.SchoolAPI;
  guest.window.eval(code+'\nwindow.testState = state;'); guest.window.showPhase('sources'); assert.equal(guest.window.testState.phase,'intro'); guest.window.close();
  console.log('PASS: student startup, anonymous navigation, code-bound submission, name stripping and live gate changes');
  const teacherDom=new JSDOM(fs.readFileSync(root+'lehrer.html','utf8'),{url:'https://school.test/lehrer.html',runScripts:'outside-only'});
  const t=teacherDom.window;
  t.HTMLDialogElement.prototype.showModal=function(){this.open=true};t.HTMLDialogElement.prototype.close=function(){this.open=false};
  t.confirm=()=>true;
  let teacherRequest;
  t.SchoolAPI={hasSession:()=>false,formatCode:v=>v,teacher:async(path,body,method)=>{
    teacherRequest={path,body,method};
    if(path.includes('teacher_profiles'))return [{user_id:teacher1}];
    if(path.includes('/rpc/replace_student_code'))return newCode;
    if(path.includes('/courses?'))return [{id:c1,name:'9a <img src=x onerror=alert(1)>',exchange_open:false}];
    if(path.includes('/course_students?'))return s1;
    if(path.includes('/course_submissions?'))return [{id:'33333333-3333-4333-8333-333333333333',student_id:s1[0].id,group_code:'A',answers:{museum_vorgehen:'Test'},submitted_at:new Date().toISOString(),reviewed:false}];
  }};
  t.eval(fs.readFileSync(root+'teacher.js','utf8')); await t.showDashboard();
  assert.equal(t.document.querySelectorAll('[data-codes]').length,1);
  assert.equal(t.document.querySelector('#courseList img'),null);
  assert.equal(t.document.querySelectorAll('#submissionRows tr').length,1);
  t.showCodes(c1); assert.equal(t.document.querySelectorAll('#codesBody tbody tr').length,2);
  await t.document.querySelector('[data-replace]').onclick();
  assert.equal(teacherRequest.path,'/rest/v1/rpc/replace_student_code');
  assert.equal(t.document.querySelector('#codesBody code').textContent,newCode);
  assert.equal(t.document.querySelector('input[type=email]'),null);
  teacherDom.window.close();
  const authDom=new JSDOM('',{url:'https://school.test/',runScripts:'outside-only'});
  const a=authDom.window;let loginBody;
  a.APP_CONFIG={SUPABASE_URL:'https://supabase.test',SUPABASE_ANON_KEY:'public'};
  a.fetch=async(url,opts)=>{loginBody=JSON.parse(opts.body);return {ok:true,json:async()=>({access_token:'token',refresh_token:'refresh',expires_at:Math.floor(Date.now()/1000)+3600})}};
  a.eval(fs.readFileSync(root+'api.js','utf8'));
  await a.SchoolAPI.login('SFischer','test-only');assert.equal(loginBody.email,'sfischer@lehrer.invalid');
  a.APP_CONFIG.TEACHER_LOGIN_ALIASES = {gymnasium:'gymnasium@kronwerk.de'};
  await a.SchoolAPI.login('Gymnasium','test-only');assert.equal(loginBody.email,'gymnasium@kronwerk.de');
  assert.equal(a.sessionStorage.getItem('clara-teacher-session-v3').includes('test-only'),false);
  await assert.rejects(a.SchoolAPI.login('bad@email','test-only'));authDom.window.close();
  for (const file of ['index.html', 'lehrer.html']) {
    const markup = fs.readFileSync(root+file, 'utf8');
    const scripts = [...markup.matchAll(/<script src="([^"]+)"/g)].map(match => match[1]);
    assert.ok(scripts.length >= 2);
    for (const src of scripts) {
      assert.match(src, /\?v=3\.0\.3$/);
      assert.ok(fs.readFileSync(root+'sw.js','utf8').includes(src));
    }
  }
  console.log('PASS: teacher dashboard, printable roster, escaped course names, code replacement, username authentication and password not stored');
}
main().catch(e=>{console.error(e);process.exit(1)});
